package com.veterinaria.control_mascota;
// Generated May 11, 2013 8:51:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Amo generated by hbm2java
 */
public class Amo  implements java.io.Serializable {


     private String idAmo;
     private String nombreAmo;
     private Set<Mascota> mascotas = new HashSet<Mascota>(0);

    public Amo() {
    }

	
    public Amo(String idAmo, String nombreAmo) {
        this.idAmo = idAmo;
        this.nombreAmo = nombreAmo;
    }
    public Amo(String idAmo, String nombreAmo, Set<Mascota> mascotas) {
       this.idAmo = idAmo;
       this.nombreAmo = nombreAmo;
       this.mascotas = mascotas;
    }
   
    public String getIdAmo() {
        return this.idAmo;
    }
    
    public void setIdAmo(String idAmo) {
        this.idAmo = idAmo;
    }
    public String getNombreAmo() {
        return this.nombreAmo;
    }
    
    public void setNombreAmo(String nombreAmo) {
        this.nombreAmo = nombreAmo;
    }
    public Set<Mascota> getMascotas() {
        return this.mascotas;
    }
    
    public void setMascotas(Set<Mascota> mascotas) {
        this.mascotas = mascotas;
    }




}


