package com.veterinaria.control_mascota;
// Generated May 11, 2013 8:51:19 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Raza generated by hbm2java
 */
public class Raza  implements java.io.Serializable {


     private String idRaza;
     private Animal animal;
     private String nombreRaza;
     private Set<Mascota> mascotas = new HashSet<Mascota>(0);

    public Raza() {
    }

	
    public Raza(String idRaza, Animal animal, String nombreRaza) {
        this.idRaza = idRaza;
        this.animal = animal;
        this.nombreRaza = nombreRaza;
    }
    public Raza(String idRaza, Animal animal, String nombreRaza, Set<Mascota> mascotas) {
       this.idRaza = idRaza;
       this.animal = animal;
       this.nombreRaza = nombreRaza;
       this.mascotas = mascotas;
    }
   
    public String getIdRaza() {
        return this.idRaza;
    }
    
    public void setIdRaza(String idRaza) {
        this.idRaza = idRaza;
    }
    public Animal getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(Animal animal) {
        this.animal = animal;
    }
    public String getNombreRaza() {
        return this.nombreRaza;
    }
    
    public void setNombreRaza(String nombreRaza) {
        this.nombreRaza = nombreRaza;
    }
    public Set<Mascota> getMascotas() {
        return this.mascotas;
    }
    
    public void setMascotas(Set<Mascota> mascotas) {
        this.mascotas = mascotas;
    }
    
}


